### ISSUE TITLE
Rename "customer model" 

### ISSUE THREAD

**Issue by laurentm255** [AI-vidence/antakia#32]
Depends on model_type

And we add (if not I uncluded), 'custom_score' from AntakIA constructor (a callable)
custom_score : defaults to 'auto'

In susbtitution table, last ligne `custom_table` is whole model

**Comment by phulot** [comment]
tu pourrais mettre un peu plus de détails là dessus ?

**Comment by laurentm255** [comment]
Easy fix. Should be renamed as "Origin model" ?
