### ISSUE TITLE
Should we display current rules on selection tab ?

### ISSUE THREAD

**Issue by laurentm255** [AI-vidence/antakia#45]
1. select points
2. find rules
3. validate rules
4. from region tab, go back to selection tab
5. you see the rule in the RuleSet widget
<img width="412" alt="image" src="https://github.com/AI-vidence/antakia/assets/47478487/12c64ca9-e1b3-4f20-8a1e-5d8439f5ba0a">

I find it somehow confusing : you don't see the rules on the figures, yet you read it below in blue ...

**Comment by phulot** [comment]
point résolu
