### ISSUE TITLE
substitution stop working

### ISSUE THREAD

**Issue by Unasc** [AI-vidence/antakia#55]
after selecting manually 2 regions (through the VS), then running autoclustering to reach 8 clusters, I substituted successfully region 1 with EBT.
But after, no more substitution was possible/ effective, with any model (tried mainly : EBT, and rigde regression)

`{
	"name": "KeyError",
	"message": "'MSE'",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/Library/Caches/pypoetry/virtualenvs/antakia-Onu_v83o-py3.11/lib/python3.11/site-packages/ipywidgets/widgets/widget.py in ?(self, *args, **kwargs)
    193                 ip = get_ipython()
    194                 if ip is None:
    195                     self.log.warning(\"Exception in callback %s: %s\", callback, e, exc_info=True)
    196                 else:
--> 197                     ip.showtraceback()
    198             else:
    199                 value = local_value if local_value is not None else value
    200         return value

~/Library/Caches/pypoetry/virtualenvs/antakia-Onu_v83o-py3.11/lib/python3.11/site-packages/ipyvue/VueWidget.py in ?(self, _, content, buffers)
    128     def _handle_event(self, _, content, buffers):
    129         event = content.get(\"event\", \"\")
    130         data = content.get(\"data\", {})
--> 131         self._fire_event(event, data)

~/Library/Caches/pypoetry/virtualenvs/antakia-Onu_v83o-py3.11/lib/python3.11/site-packages/ipyvue/VueWidget.py in ?(self, event, data)
    122     def _fire_event(self, event, data=None):
    123         dispatcher = self._event_handlers_map[event]
    124         # we don't call via the dispatcher, since that eats exceptions
    125         for callback in dispatcher.callbacks:
--> 126             callback(self, event, data or {})

~/Code/antakia/antakia/gui/gui.py in ?(*args)
    467         def call_fct(*args):
--> 468             self.select_tab(tab, front=True)

~/Code/antakia/antakia/gui/gui.py in ?(self, tab, front)
    480             self.vs_hde.display_regionset(self.region_set)
    481             self.es_hde.display_regionset(self.region_set)
    482         elif tab == 3:
    483             region = self.region_set.get(self.selected_region_num)
--> 484             self.update_substitution_table(region)
    485             if region is None:
    486                 region = ModelRegion(self.X, self.y, self.model, score=self.score)
    487             self.vs_hde.display_region(region)

~/Code/antakia/antakia/gui/gui.py in ?(self, region)
    727                 prog_circular.color = \"blue\"
    728                 prog_circular.indeterminate = True
    729                 # We clear items int the SubModelTable
    730                 get_widget(app_widget, \"45001\").items = []
--> 731             elif len(region.perfs) == 0:
    732                 # We have no results
    733                 vHtml.class_ = \"ml-2 red--text\"
    734                 vHtml.tag = \"h3\"

~/Code/antakia/antakia/data_handler/region.py in ?(self)
     91     @property
     92     def perfs(self):
---> 93         return self.interpretable_models.perfs.sort_values(self.interpretable_models.custom_score_str, ascending=True)

~/Library/Caches/pypoetry/virtualenvs/antakia-Onu_v83o-py3.11/lib/python3.11/site-packages/pandas/core/frame.py in ?(self, by, axis, ascending, inplace, kind, na_position, ignore_index, key)
   6940             )
   6941         elif len(by):
   6942             # len(by) == 1
   6943 
-> 6944             k = self._get_label_or_level_values(by[0], axis=axis)
   6945 
   6946             # need to rewrap column in Series to apply key function
   6947             if key is not None:

~/Library/Caches/pypoetry/virtualenvs/antakia-Onu_v83o-py3.11/lib/python3.11/site-packages/pandas/core/generic.py in ?(self, key, axis)
   1840             values = self.xs(key, axis=other_axes[0])._values
   1841         elif self._is_level_reference(key, axis=axis):
   1842             values = self.axes[axis].get_level_values(key)._values
   1843         else:
-> 1844             raise KeyError(key)
   1845 
   1846         # Check for duplicates
   1847         if values.ndim > 1:

KeyError: 'MSE'"
}`

<img width="1366" alt="image" src="https://github.com/AI-vidence/antakia/assets/86070402/3cc1cbaa-a6af-4b35-b06d-cd233fb56986">

**Comment by phulot** [comment]
prb de num de points dans le cluster, cas maintenant géré
