### ISSUE TITLE
Clear SubModelTable selection

### ISSUE THREAD

**Issue by phulot** [AI-vidence/antakia#84]
une fois un modèle validé pour une région, ce modèle reste selectionné sur le substitute de la région suivante, mais le validate n'est pas disponible

**Comment by laurentm255** [comment]
J'ai du mal à retrouver mon code à vrai dire.

Je comprends que lorsqu'on clique sur "validate" (pour désigner un submodel), il faut enlever toute sélection de la SubModelTable...
