### ISSUE TITLE
Splash screen is displayed as text instead of widget @ reloads

### ISSUE THREAD

**Issue by phulot** [AI-vidence/antakia#85]
when antakia is launched a 2nd time, a text is displayed
![image](https://github.com/AI-vidence/antakia/assets/12272071/182faa0e-b320-453a-961c-93d002cabab2)

**Comment by laurentm255** [comment]
This text is displayed **in place of displaying the splash screen.** As a matter of fact, the text described the widget graph of the splash screen.

I need to further investigate
